// Human-readable report generation for a pipeline run — the PR body a `low-risk` run puts up for
// auto-merge, and the single tracked issue body a `hard-stop`/manual-review run updates. Pure
// string-building, no I/O, so it's trivially unit-testable.

/** Stable marker so run.mjs can find-and-update one existing issue instead of spamming a new one
 * every scheduled run (docs/adr/0004-public-data-ingestion.md section 8 "tránh spam"). */
export const SOURCE_HEALTH_ISSUE_MARKER = '<!-- daklak-data-refresh-source-health -->';

/**
 * @param {{ datasetId: string, riskLevel: 'low-risk'|'hard-stop', reasons: string[],
 *   diff: { added: unknown[], removed: unknown[], changed: unknown[], unchangedCount: number },
 *   runStatus: string }} input
 */
export function buildPrReportMarkdown(input) {
  const { datasetId, riskLevel, reasons, diff, runStatus } = input;
  const lines = [
    `# Data refresh: ${datasetId}`,
    '',
    `**Run status:** \`${runStatus}\` · **Risk:** \`${riskLevel}\``,
    '',
    '## Diff summary',
    `- Added: ${diff.added.length}`,
    `- Removed: ${diff.removed.length}`,
    `- Changed: ${diff.changed.length}`,
    `- Unchanged: ${diff.unchangedCount}`,
  ];
  if (reasons.length > 0) {
    lines.push('', '## Reasons this is not auto-merged', ...reasons.map((reason) => `- ${reason}`));
  } else {
    lines.push('', 'No hard-stop conditions found — eligible for auto-merge.');
  }
  lines.push(
    '',
    '_Generated by scripts/data-refresh/run.mjs — see docs/adr/0004-public-data-ingestion.md._',
  );
  return lines.join('\n');
}

/**
 * @param {{ datasetId: string, riskLevel: 'low-risk'|'hard-stop', reasons: string[], checkedAt: string }} input
 */
export function buildSourceHealthIssueBody(input) {
  const { datasetId, riskLevel, reasons, checkedAt } = input;
  const lines = [
    SOURCE_HEALTH_ISSUE_MARKER,
    `# Source health: ${datasetId}`,
    '',
    `Last checked: ${checkedAt}`,
    `Status: \`${riskLevel}\``,
    '',
  ];
  if (reasons.length > 0) {
    lines.push('## Open issues', ...reasons.map((reason) => `- ${reason}`));
  } else {
    lines.push('No open issues.');
  }
  return lines.join('\n');
}
