// Human-readable report generation for a pipeline run — the PR body a `low-risk` run puts up for
// auto-merge, and the single tracked issue body a `hard-stop`/manual-review run updates. Pure
// string-building, no I/O, so it's trivially unit-testable.

/** Stable marker so run.mjs can find-and-update one existing issue instead of spamming a new one
 * every scheduled run (docs/adr/0004-public-data-ingestion.md section 8 "tránh spam"). */
export const SOURCE_HEALTH_ISSUE_MARKER = '<!-- daklak-data-refresh-source-health -->';

/**
 * @param {{ datasetId: string, riskLevel: 'low-risk'|'hard-stop', reasons: string[],
 *   diff: { added: unknown[], removed: unknown[], changed: unknown[], unchangedCount: number },
 *   runStatus: string, maturity: string, autoMergeEligible: boolean, autoMergeReasons: string[] }} input
 */
export function buildPrReportMarkdown(input) {
  const {
    datasetId,
    riskLevel,
    reasons,
    diff,
    runStatus,
    maturity,
    autoMergeEligible,
    autoMergeReasons,
  } = input;
  const lines = [
    `# Data refresh: ${datasetId}`,
    '',
    `**Run status:** \`${runStatus}\` · **Risk:** \`${riskLevel}\` · **Source maturity:** \`${maturity}\``,
    '',
    '## Diff summary',
    `- Added: ${diff.added.length}`,
    `- Removed: ${diff.removed.length}`,
    `- Changed: ${diff.changed.length}`,
    `- Unchanged: ${diff.unchangedCount}`,
  ];
  if (reasons.length > 0) {
    lines.push(
      '',
      '## Reasons this run is not low-risk',
      ...reasons.map((reason) => `- ${reason}`),
    );
  }
  lines.push('', autoMergeEligible ? '## Auto-merge' : '## Manual review required');
  if (autoMergeEligible) {
    lines.push('This run is eligible for auto-merge — no hard conditions failed.');
  } else {
    lines.push(
      `@shadowhunter67 — this run requires manual review before merge:`,
      ...autoMergeReasons.map((reason) => `- ${reason}`),
    );
  }
  lines.push(
    '',
    '_Generated by scripts/data-refresh/run.mjs — see docs/adr/0004-public-data-ingestion.md._',
  );
  return lines.join('\n');
}

/**
 * @param {{ datasetId: string, riskLevel: 'low-risk'|'hard-stop', reasons: string[], checkedAt: string }} input
 */
export function buildSourceHealthIssueBody(input) {
  const { datasetId, riskLevel, reasons, checkedAt } = input;
  const lines = [
    SOURCE_HEALTH_ISSUE_MARKER,
    `# Source health: ${datasetId}`,
    '',
    `@shadowhunter67 — this source needs manual review.`,
    '',
    `Last checked: ${checkedAt}`,
    `Status: \`${riskLevel}\``,
    '',
  ];
  if (reasons.length > 0) {
    lines.push('## Open issues', ...reasons.map((reason) => `- ${reason}`));
  } else {
    lines.push('No open issues.');
  }
  return lines.join('\n');
}
