/**
 * `InvestmentOpportunity` — danh mục cơ hội đầu tư/xúc tiến đầu tư công khai, hoàn toàn KHÁC
 * `Project` (`src/entities/project/`, dự án trọng điểm đang vận hành — xem
 * docs/adr/0001-project-centric-domain.md). Xem docs/adr/0004-public-data-ingestion.md mục 1 cho lý
 * do tách biệt: một cơ hội đầu tư có thể chưa từng được duyệt, chưa có nhà đầu tư, và đến từ danh
 * mục xúc tiến đầu tư công khai (nguồn của pipeline này) — không phải dữ liệu vận hành dự án.
 *
 * File này KHÔNG import bất cứ gì từ `src/entities/project/`, và ngược lại — hai domain không dùng
 * chung enum dù bề ngoài có thể giống nhau (ví dụ trạng thái "đang triển khai" của Project khác hẳn
 * ý nghĩa "đang mời gọi đầu tư" ở đây).
 */

export const INVESTMENT_OPPORTUNITY_STATUSES = [
  'announced',
  'open-for-proposals',
  'under-review',
  'awarded',
  'withdrawn',
  'expired',
  'unknown',
] as const;
export type InvestmentOpportunityStatus = (typeof INVESTMENT_OPPORTUNITY_STATUSES)[number];

export const INVESTMENT_SECTORS = [
  'transport',
  'energy',
  'irrigation',
  'health',
  'education',
  'urban-development',
  'digital-transformation',
  'industrial-zone',
  'agriculture',
  'tourism',
  'other',
] as const;
export type InvestmentSector = (typeof INVESTMENT_SECTORS)[number];

export interface InvestmentOpportunity {
  id: string;
  /** Human-readable code as published by the source, if any — not generated by this app. */
  sourceCode?: string;
  title: string;
  sector: InvestmentSector;
  status: InvestmentOpportunityStatus;
  /** Administrative codes this opportunity is explicitly linked to — same code space as
   * `daklak-labels.json`, but this entity never imports GIS assets directly (same import-boundary
   * rule as `src/entities/project/`, see `importBoundary.test.ts`). */
  administrativeAreaCodes: string[];
  /** Estimated investment scale as published by the source — a range, not a single figure, since
   * public investment-promotion listings rarely commit to an exact number pre-award. */
  estimatedInvestmentVndMin?: number;
  estimatedInvestmentVndMax?: number;
  proposalDeadline?: string;
  /** `sourceDatasetId` must point at a dataset registered in `data/source-registry.yml` — this
   * entity never carries data it cannot trace back to a declared source. */
  sourceDatasetId: string;
  /** When this record was last confirmed to still reflect the source (retrievedAt from the
   * refresh manifest that produced/updated it) — see scripts/data-refresh/manifest.mjs. */
  retrievedAt: string;
  description?: string;
}
